## os.path.join()

In [6]:
import os

DIRECTORY = "C:\\Users\\Autonav\\github_repo\\SLAM\\VisualOdometry_py\\main\\KITTI_sequence_1\\image_l"
filename = "000000.png"
print(os.path.join(DIRECTORY, filename))

C:\Users\Autonav\github_repo\SLAM\VisualOdometry_py\main\KITTI_sequence_1\image_l\000000.png


## cv2.ORB_create() / detectAndCompute / cv2.drawKeypoints()

In [4]:
import cv2

img = cv2.imread('../main/building.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# ORB detector 생성
orb = cv2.ORB_create()
"""
nfeatures(optional): 검출할 최대 특징 수 (default=500)
scaleFactor(optional): 이미지 피라미드 비율 (default=1.2)
nlevels(optional): 이미지 피라미드 계층 수 (default=8)
edgeThreshold(optional): 검색에서 제외할 테두리 크기, patchSize와 맞출 것 (default=31)
firstLevel(optional): 최초 이미지 피라미드 계층 단계 (default=0)
WTA_K(optional): 임의 좌표 생성 수 (default=2)
scoreType(optional): 특징점 검출에 사용할 방식 (cv2.ORB_HARRIS_SCORE: 해리스 코너 검출(default), cv2.ORB_FAST_SCORE: FAST 코너 검출)
patchSize(optional): 디스크립터의 패치 크기 (default=31)
fastThreshold(optional): FAST에 사용할 임계 값 (default=20)
"""
# 특징점 검출(detect)과 desciptor 추출(compute)
# descriptor는 특징점 주변 픽셀을 일정 크기의 블록으로 나누어 각 블록에 속한 픽셀의 그레디언트 히스토그램을 계산한 것.
keypoints, descriptor = orb.detectAndCompute(img, None)

# 특징점 그리기 - OpenCV에서 cv2.drawKeypoints() 제공해서 cv2.circle로 특징점 나타낼 필요 없음.
img_draw = cv2.drawKeypoints(img, keypoints, None, \
             flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)

# 결과 출력
cv2.imshow('ORB', img_draw)
cv2.waitKey()
cv2.destroyAllWindows()

## cv2.FlannBasedMatcher() / knnMatch() / cv2.drawMatches()

In [7]:
# FLANNMatcher와 ORB로 매칭 (match_flann_orb.py)

import cv2, numpy as np

img1 = cv2.imread('../main/KITTI_sequence_1/image_l/000000.png')
img2 = cv2.imread('../main/KITTI_sequence_1/image_l/000001.png')
gray1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
gray2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# ORB 추출기 생성
detector = cv2.ORB_create() 
# 키 포인트와 서술자 추출
kp1, desc1 = detector.detectAndCompute(gray1, None)
kp2, desc2 = detector.detectAndCompute(gray2, None)

# 인덱스 파라미터 설정 ---①
FLANN_INDEX_LSH = 6
index_params= dict(algorithm = FLANN_INDEX_LSH,
                   table_number = 6,
                   key_size = 12,
                   multi_probe_level = 1)
# 검색 파라미터 설정 ---②
search_params=dict(checks=32)
# Flann 매처 생성 ---③
matcher = cv2.FlannBasedMatcher(index_params, search_params)    # BFMatcher()도 있다.
# 매칭 계산 ---④
matches = matcher.match(desc1, desc2)   # 여기에 match(), knnMatch()(k-nearest neighbor), radiusMatch()를 이용가능
# 매칭 그리기
res = cv2.drawMatches(img1, kp1, img2, kp2, matches, None, \
            flags=cv2.DRAW_MATCHES_FLAGS_NOT_DRAW_SINGLE_POINTS)
# 결과 출력            
cv2.imshow('Flann + ORB', res)
cv2.waitKey()
cv2.destroyAllWindows()

## np.squeeze()

In [8]:
import numpy as np

a = np.array([[[[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]]]])

print(a.shape, "\n")


print(np.squeeze(a))

(1, 1, 3, 3) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## tqdm

In [9]:
from tqdm import tqdm
import time

text = ""

for x in tqdm(["a", "b", "c", "d"]):
    time.sleep(1)
    text = text + x


100%|██████████| 4/4 [00:04<00:00,  1.00s/it]
